[package]
name = "sol-vault"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
solana-program = "=2.0.3"
borsh-derive = "1.5.1"

[features]
test-bpf = []

[lib]
name = "solvault"
crate-type = ["cdylib", "lib"]
